#!/bin/bash
set -ex

dep ensure
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o kube-mutating-webhook-tutorial .
docker build --no-cache -t falfaro/sidecar-injector:latest .
rm -rf kube-mutating-webhook-tutorial
docker push falfaro/sidecar-injector:latest
