---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingress-webhook-deployment
  namespace: kubeprod
  labels:
    app: ingress-webhook
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ingress-webhook
    spec:
      containers:
        - name: ingress-webhook
          image: falfaro/sidecar-injector:latest
          imagePullPolicy: Always
          args:
            - -dnsSuffix=eks.felipe-alfaro.com
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: ingress-webhook-certs
