---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: ingress-webhook-cfg
  labels:
    app: ingress-webhook
webhooks:
  - name: ingress-webhook.kubeprod.io
    clientConfig:
      service:
        name: ingress-webhook-svc
        namespace: kubeprod
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations:
          - "CREATE"
          - "UPDATE"
        apiGroups:
          - "extensions"
        apiVersions:
          - "v1beta1"
        resources:
          - "ingresses"
