---
apiVersion: v1
kind: Service
metadata:
  name: ingress-webhook-svc
  namespace: kubeprod
  labels:
    app: ingress-webhook
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: ingress-webhook
